name = "MathOptScaling"
uuid = "b8875808-0e9a-4e84-a8da-9a0830c3b149"
version = "0.1.0"
authors = ["Klamkin, Michael <mklamkin3@gatech.edu>"]

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[weakdeps]
Atomix = "a9b6321e-bd34-4604-b9c9-b65b8de01458"
GPUArrays = "0c68f7d7-f131-5f86-a1c3-88cf8149b2d7"
KernelAbstractions = "63c18a36-062a-441e-b654-da1e3ab1ce7c"

[extensions]
MathOptScalingKernelAbstractionsExt = ["Atomix", "GPUArrays", "KernelAbstractions"]

[compat]
Atomix = "1"
GPUArrays = "11"
KernelAbstractions = "0.9"
LinearAlgebra = "1.10"
SparseArrays = "1.10"
julia = "1.10"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
